### ISSUE TITLE
Not able to read property when it has "-" in name.

### ISSUE THREAD

**Issue by ramnaresh2051** [j-easy/easy-rules#167]
Not able to read property when it has "-" in name. We have a requirement where we have to compare some headers against the rules, but these contains "-" in name i.e. X-Test-Header, once I am defining this in .yml file and firing the rule its not working.
I am using MVELRuleFactory to load rules from .yml file, below is sample file.

```yaml
---
name: " redirection1"
description: "redirection"
priority: 20
condition: "X-Test-Header == 'somevalue'"
actions:
  - "hidden-url = 'localhost:8080/api/v2/test';"
```

```
16:45:03.221 [main] INFO org.jeasy.rules.core.DefaultRulesEngineListener - Rules evaluation started
16:45:03.249 [main] DEBUG org.jeasy.rules.mvel.MVELCondition - Unable to evaluate expression: 'X-Test-Header == 'somevalue'' on facts: [ { X-Test-Header : test.gsx.corp.apple.com:8080/api/v1/somevalue } ]
org.mvel2.PropertyAccessException: [Error: unresolvable property or identifier: X]
[Near : {... X-Test-Header == 'somevalue' ....}]
             ^
[Line: 1, Column: 1]
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.getBeanProperty(ReflectiveAccessorOptimizer.java:703)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.compileGetChain(ReflectiveAccessorOptimizer.java:360)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.optimizeAccessor(ReflectiveAccessorOptimizer.java:163)
	at org.mvel2.optimizers.dynamic.DynamicOptimizer.optimizeAccessor(DynamicOptimizer.java:80)
	at org.mvel2.ast.ASTNode.optimize(ASTNode.java:159)
	at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:115)
	at org.mvel2.ast.BinaryOperation.getReducedValueAccelerated(BinaryOperation.java:117)
	at org.mvel2.ast.BinaryOperation.getReducedValueAccelerated(BinaryOperation.java:117)
	at org.mvel2.ast.BinaryOperation.getReducedValueAccelerated(BinaryOperation.java:117)
	at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:42)
	at org.mvel2.MVEL.executeExpression(MVEL.java:968)
	at org.jeasy.rules.mvel.MVELCondition.evaluate(MVELCondition.java:59)
	at org.jeasy.rules.mvel.MVELRule.evaluate(MVELRule.java:107)
	at org.jeasy.rules.core.DefaultRulesEngine.doFire(DefaultRulesEngine.java:112)
	at org.jeasy.rules.core.DefaultRulesEngine.fire(DefaultRulesEngine.java:94)
	at com.ram.RuleTestOne.main(RuleTestOne.java:47)
```

**Comment by ramnaresh2051** [comment]
I have used map from java side and then define the .yml in below manner. And its working fine now.

---
name: " redirection1"
description: "redirection"
priority: 20
condition: "req['X-Test-Header'] == 'somevalue'"
actions:
  - "req['hidden-url'] = 'localhost:8080/api/v2/test';"
