### ISSUE TITLE
Json/Yaml based rule definition for SPEL crashes

### ISSUE THREAD

**Issue by shiv4289** [j-easy/easy-rules#222]
**Steps to reproduce**
1. Place the below code in SpELRuleTest.java (latest master)
2. Run the below test
3. The test crashes

> @Test
> public void whenSpELRuleIsInitializedFromJsonFile_crashes() throws Exception {
> 
>     // Create Rule
>     SpELRuleFactory factory = new SpELRuleFactory(new JsonRuleDefinitionReader());
>     File rulesDescriptor = new File("src/test/resources/adult-rule.json");
>     Rules rules = factory.createRules(new FileReader(rulesDescriptor));
> 
>     // Make facts
>     Person foo = new Person("foo", 20);
>     facts.put("person", foo);
> 
>     // Execute Rule
>     RulesEngine rulesEngine = new DefaultRulesEngine();
>     rulesEngine.fire(rules, facts);
> 
>     // assert
>     assertThat(foo.isAdult()).isTrue();
> }

**Comment by shiv4289** [comment]
**stacktrace:**

> [main] ERROR org.jeasy.rules.spel.SpELCondition - Unable to evaluate expression: '#person.age > 18' on facts: [ { person : org.jeasy.rules.spel.Person@29b5cd00 } ]
> org.springframework.expression.spel.SpelEvaluationException: EL1001E: Type conversion problem, cannot convert from java.lang.String to java.lang.Boolean
> 	at org.springframework.expression.spel.support.StandardTypeConverter.convertValue(StandardTypeConverter.java:75)
> 	at org.springframework.expression.common.ExpressionUtils.convertTypedValue(ExpressionUtils.java:57)
> 	at org.springframework.expression.common.LiteralExpression.getValue(LiteralExpression.java:92)
> 	at org.jeasy.rules.spel.SpELCondition.evaluate(SpELCondition.java:81)
> 	at org.jeasy.rules.spel.SpELRule.evaluate(SpELRule.java:130)
> 	at org.jeasy.rules.core.DefaultRulesEngine.doFire(DefaultRulesEngine.java:83)
> 	at org.jeasy.rules.core.DefaultRulesEngine.fire(DefaultRulesEngine.java:65)
> 	at org.jeasy.rules.spel.SpELRuleTest.whenSpELRuleIsInitializedFromJsonFile_crashes(SpELRuleTest.java:101)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
> 	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
> 	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
> 	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
> 	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
> Caused by: org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [java.lang.Boolean] for value '#person.age > 18'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value '#person.age > 18'
> 	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:46)
> 	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:191)
> 	at org.springframework.expression.spel.support.StandardTypeConverter.convertValue(StandardTypeConverter.java:70)
> 	... 30 more
> Caused by: java.lang.IllegalArgumentException: Invalid boolean value '#person.age > 18'
> 	at org.springframework.core.convert.support.StringToBooleanConverter.convert(StringToBooleanConverter.java:63)
> 	at org.springframework.core.convert.support.StringToBooleanConverter.convert(StringToBooleanConverter.java:31)
> 	at org.springframework.core.convert.support.GenericConversionService$ConverterAdapter.convert(GenericConversionService.java:385)
> 	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:40)
> 	... 32 more
> 
> org.junit.ComparisonFailure: 
> Expected :true
> Actual   :false

**Comment by shiv4289** [comment]
In the test code pasted above, if I replace the first three lines of java code with the following code, it works:

>     Rules rules = new Rules();
>     rules.register(spelRule);

Digging more into this I see that in the Json file based rule case , the compiledExpression attribute in SpELCondition.java resolves to LiteralExpression.java implementation

In the working code in this comment though it resolves to SpelExpression.java. This difference is a consequence of this code:

>     public Rules createRules(Reader rulesDescriptor) throws Exception {
>         return createRules(rulesDescriptor, new TemplateParserContext());
>     }

Not sure what the fix here should be though...

**Comment by shiv4289** [comment]
Not a bug, the json file src/test/resources/adult-rule.json does not present conditions as spel syntax. This content works fine

> [
>   {
>     "name": "adult rule",
>     "description": "when age is greater then 18, then mark as adult",
>     "priority": 1,
>     "condition": "#{#person.getAge() > 18}",
>     "actions": [
>       "#{#person.setAdult(true)};"
>     ]
>   }
> ]
