### ISSUE TITLE
Lambda expressions are not evaluated in condition. 

### ISSUE THREAD

**Issue by Azmechatech** [j-easy/easy-rules#245]
Lambda expressions are not evaluated in condition. 

I get following errors for expression below:
 bs.getB().getR().getENames().entrySet().stream().allMatch(entry -> entry.getValue().dayCatPDi.size() == 5)
....
[Line: 1, Column: 105]
at org.mvel2.compiler.ExpressionCompiler._compile(ExpressionCompiler.java:305)
at org.mvel2.compiler.ExpressionCompiler.compile(ExpressionCompiler.java:67)
at org.mvel2.MVEL.analyze(MVEL.java:680)
at org.mvel2.compiler.PropertyVerifier.getMethod(PropertyVerifier.java:526)
at org.mvel2.compiler.PropertyVerifier.analyze(PropertyVerifier.java:135)
at org.mvel2.compiler.ExpressionCompiler.verify(ExpressionCompiler.java:399)
at org.mvel2.compiler.ExpressionCompiler._compile(ExpressionCompiler.java:281)
at org.mvel2.util.ParseTools.subCompileExpression(ParseTools.java:2083)
at org.mvel2.ast.TypedVarNode.<init>(TypedVarNode.java:52)
at org.mvel2.compiler.AbstractParser.procTypedNode(AbstractParser.java:1461)
at org.mvel2.compiler.AbstractParser.nextToken(AbstractParser.java:842)
at org.mvel2.compiler.AbstractParser.nextTokenSkipSymbols(AbstractParser.java:241)
at org.mvel2.compiler.ExpressionCompiler._compile(ExpressionCompiler.java:164)
at org.mvel2.compiler.ExpressionCompiler.compile(ExpressionCompiler.java:67)
at org.mvel2.MVEL.compileExpression(MVEL.java:810)
at org.jeasy.rules.mvel.MVELAction.<init>(MVELAction.java:65)
at org.jeasy.rules.mvel.MVELRule.then(MVELRule.java:122)
at org.jeasy.rules.mvel.MVELRuleFactory.createSimpleRule(MVELRuleFactory.java:195)
at org.jeasy.rules.mvel.MVELRuleFactory.createRule(MVELRuleFactory.java:184)
at org.jeasy.rules.mvel.MVELRuleFactory.createRules(MVELRuleFactory.java:146)
at org.jeasy.rules.mvel.MVELRuleFactory.createRules(MVELRuleFactory.java:133)

**Comment by zhhaojie** [comment]
@Azmechatech  MVEL, SpEL don't support streaming API.
you can do like this:
```
boolean dayCatPDiSizeGt5(){
return bs.getB().getR().getENames().entrySet().stream().allMatch(entry -> entry.getValue().dayCatPDi.size() == 5);
}
```
at last , in yaml file call `xx.dayCatPDiSizeGt5()`.

**Comment by Azmechatech** [comment]
I wanted to avoid writing a code for rule, as this is more of a case specific logic.  Is there a plan to include support for streaming API or lambda functions?

**Comment by benas** [comment]
+1 to what @zhhaojie said. Personally, I'm not a fan of coding in yaml/json/etc, I would write the function In Java and call them from the rule descriptor.

That said, Easy rules v3.x is based on Java 7 (Java 8 is planned for v4). I'm not sure if this is related to the issue (There is no minimal code example I can run to confirm that), but I'm adding this info here as a reference.

> Is there a plan to include support for streaming API or lambda functions?

What could Easy Rules do to add support for that? That is not a feature to add in Easy Rules, but a feature to request against MVEL and SpEL.

I'm closing this issue for now, but do not hesitate to add a comment if necessary.

**Comment by shabir1** [comment]
@benas  Can we set default action if none of the rules are triggered?
