### ISSUE TITLE
multiple rules in rule descriptor

### ISSUE THREAD

**Issue by ghost** [j-easy/easy-rules#416]
hey,

i want to give a customer the possibility to write a .yml file that i read from for the programm. I was wondering if it is possible to have multiple rules in a rule descriptor .yml. In the examples there is always only one rule, if there is a way to read more rules i would really want to know how this could be achieved. Thank you in advance!

**Comment by zhhaojie** [comment]
Of course it can be supported, you can take a look at this implementation class.

[https://github.com/j-easy/easy-rules/blob/master/easy-rules-support/src/main/java/org/jeasy/rules/support/reader/YamlRuleDefinitionReader.java](url)

Finally, load them when your app started.

**Comment by ghost** [comment]
aah, i was too quick there, found it when studying the yaml definitions. Thank you anyway sir this would have also helped, sure

**Comment by CloudWangASP** [comment]
I try to fire this rules below, then failed, is  there any issues in my Yml?

--------------------------------------------------------------------
rules:
- name: "weather rule"
  description: "if it rains then take an umbrella"
  condition: "rain == true"
  actions:
    - "System.out.println(\"It rains, take an umbrella!\");"

- name: "temperature rule"
  description: "if the temperature is below 20 then wear a jacket"
  condition: "temp < 20"
  actions:
    - "System.out.println(\"It is cold, wear a jacket!\");"

----------------------------------------------------------------------------------------

java.lang.IllegalArgumentException: The rule condition must be specified
at org.jeasy.rules.support.reader.AbstractRuleDefinitionReader.createRuleDefinition(AbstractRuleDefinitionReader.java:81)
at org.jeasy.rules.support.reader.AbstractRuleDefinitionReader.read(AbstractRuleDefinitionReader.java:45)
at org.jeasy.rules.mvel.MVELRuleFactory.createRules(MVELRuleFactory.java:100)

**Comment by ghost** [comment]
Hey, yes in your condition your are missing to call the class you passed to the rule. "Rain" and "temp" are likely or even have to be properties of the class you are passing to the rule via facts.put(nameToUseInYml, yourClassInstance), so in the condition you need to call it like "nameToUseInYml.rain" and "nameToUseInYml.temp". Like this you can also call methods of that class where you can put in parameters. You can f.e. define a method for ur class that returns a bool and call this in your condition, f.e. if u need more complex programm logic. The same goes for the action.
