### ISSUE TITLE
Crash when using @Priority

### ISSUE THREAD

**Issue by matthew-carroll** [j-easy/easy-rules#93]
I had rules executing, but when I try to use @Priority to order them, I get the following crash when adding the rule to the engine:

java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy21.getPriority(Unknown Source)
	at org.easyrules.core.RuleProxy.compareTo(RuleProxy.java:111)
	at org.easyrules.core.RuleProxy.invoke(RuleProxy.java:103)
	at com.sun.proxy.$Proxy21.compareTo(Unknown Source)
	at java.util.TreeMap.compare(TreeMap.java:1294)
	at java.util.TreeMap.put(TreeMap.java:538)
	at java.util.TreeSet.add(TreeSet.java:255)
	at org.easyrules.core.DefaultRulesEngine.registerRule(DefaultRulesEngine.java:81)

This is on version 2.5.0

**Comment by matthew-carroll** [comment]
Actually, I think the issue may be a private access modifier on the class.  I changed it because the IDE was complaining.  I'll verify and then post back.

**Comment by matthew-carroll** [comment]
Ok, @priority is working now that I changed the rule classes back to public to work with reflection.
